server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/jgdb?serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

mybatis-plus:
  type-aliases-package: com.chx.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chx.dao: debug
